@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


Person(personAlias, "Aplicação WEB", "Optional Description")
Container(containerAlias, "Api", "BackEnd", "Regra de negocio")
System(systemAlias, "Base de Dados", "Armazenar tarefas")


Rel(personAlias, containerAlias, "HTTPS", "APLICAÇÃO")
Rel(containerAlias, systemAlias, "JDBC", "CONEXÃO")
@enduml